# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/autosave.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/gitgutter.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/whitespace.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/quickrun.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/easymotion.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'source ~/dotfiles/.vim/autoload/hyokoji/vimproc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

